# Generated by Django 2.0.2 on 2019-07-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cant_km',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='height',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='weight',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='direccion'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, choices=[('1', 'AREQUIPA'), ('2', 'AREQUIPA - CAMANA'), ('3', 'AREQUIPA - CIUDAD MAJES'), ('4', 'AREQUIPA - MOLLENDO'), ('5', 'AREQUIPA - PEDREGAL'), ('6', 'CUSCO'), ('7', 'JULIACA'), ('8', 'TACNA'), ('9', 'OTRA CIUDAD')], max_length=2, null=True, verbose_name='ciudad'),
        ),
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.CharField(blank=True, choices=[('1', 'ALTO SELVA ALEGRE'), ('2', 'AREQUIPA'), ('3', 'CAYMA'), ('4', 'CERRO COLORADO'), ('5', 'CHARACATO'), ('6', 'CHIGUATA'), ('7', 'JACOBO HUNTER'), ('8', 'JLB Y RIVERO'), ('9', 'LA JOYA'), ('10', 'MARIANO MELGAR'), ('11', 'MIRAFLORES'), ('12', 'MOLLEBAYA'), ('13', 'PAUCARPATA'), ('14', 'POCSI'), ('15', 'POLOBAYA'), ('16', 'QUEQUEÑA'), ('17', 'SABANDIA'), ('18', 'SACHACA'), ('19', 'SAN JUAN DE TARUCANI'), ('20', 'SANTA ISABEL DE SIGUAS'), ('21', 'SANTA RITA DE SIGUAS'), ('22', 'SAN JUAN DE SIGUAS'), ('23', 'SOCABAYA'), ('24', 'TIABAYA'), ('25', 'VITOR'), ('26', 'YANAHUARA'), ('27', 'YARABAMBA'), ('28', 'YURA'), ('29', 'OTRO DISTRITO')], max_length=2, null=True, verbose_name='distrito'),
        ),
        migrations.AddField(
            model_name='profile',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='dni'),
        ),
    ]
