# Generated by Django 2.0.2 on 2019-06-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='dirección')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='imagen')),
                ('value_km', models.IntegerField(blank=True, null=True, verbose_name='cantidad de km')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tienda',
            },
        ),
    ]
