# Generated by Django 2.0.2 on 2019-06-26 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bici', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='store',
            name='updated_at',
        ),
    ]
