# Generated by Django 2.0.2 on 2019-06-27 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bici', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='latitud')),
                ('length', models.FloatField(verbose_name='longitud')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ubicacion',
            },
        ),
    ]
