# Generated by Django 2.0.2 on 2019-06-27 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bici', '0002_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='length',
            new_name='longitude',
        ),
    ]
