# Generated by Django 2.0.2 on 2019-07-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bici', '0003_auto_20190626_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(verbose_name='km')),
                ('speed', models.FloatField(verbose_name='velocidad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ruta',
            },
        ),
        migrations.RemoveField(
            model_name='store',
            name='image',
        ),
    ]
