# Generated by Django 2.0.2 on 2019-07-11 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bici', '0004_auto_20190711_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='bici.Route'),
            preserve_default=False,
        ),
    ]
